"""empty message

Revision ID: df6df3733474
Revises: a997ebc734b5
Create Date: 2019-04-16 19:48:24.264127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df6df3733474'
down_revision = 'a997ebc734b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('all_time_job', sa.Column('category', sa.String(length=64), nullable=True))
    op.add_column('part_time_job', sa.Column('category', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('part_time_job', 'category')
    op.drop_column('all_time_job', 'category')
    # ### end Alembic commands ###
